CREATE TABLE IF NOT EXISTS users (
  id        INT AUTO_INCREMENT PRIMARY KEY,
  email     VARCHAR(255) UNIQUE NOT NULL,
  password  VARCHAR(60)  NOT NULL,  -- bcrypt hash
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
